spring.application.name=demo
server.port=8082

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=0dln6C4FpMH8wsfs4xd+MJ/YfTjHRrzyKje08rgma1A=
jwt.expiration=3600000
jwt.refresh-expiration=604800000